version: 2.1
jobs:
  lint:
    docker:
      - image: python:3.9

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run PEP8 tests
          command: |
            flake8 .
            isort .
            black --check .
            interrogate -v

workflows:
  version: 2
  lint_workflow:
    jobs:
      - lint
