version: 2.1
jobs:
  build:
    docker:
      - image: python:3.9  # Use an image with required Python version

    steps:
      - checkout  # Checkout the code from GitHub

      # Install dependencies
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      # Linting with flake8
      - run:
          name: Lint with flake8
          command: flake8 --exclude=venv* .

      # Other steps like testing, building, etc. can be added here
