version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Use Python 3.9 as an example, replace with your preferred image
    steps:
      - checkout

      # Start Docker service
      - run:
          name: Start Docker Service
          command: sudo service docker start

      # Install Docker Compose (if needed)
      # - run:
      #     name: Install Docker Compose
      #     command: |
      #       sudo curl -L https://github.com/docker/compose/releases/download/<DOCKER_COMPOSE_VERSION>/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      #       sudo chmod +x /usr/local/bin/docker-compose

      # PEP8 checks using Interrogate and other tools
      - run:
          name: Run PEP8 checks
          command: |
            pip install flake8 isort black interrogate  # Install necessary libraries
            flake8 .  # Check PEP8 compliance
            isort . --check-only  # Check import sorting
            black . --check --diff  # Check code formatting
            interrogate -v -c path/to/interrogate-config-file .  # Run Interrogate (replace with your config file)

      # Login to DockerHub and push the Docker image
      - run:
          name: Push Docker Image to DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push your-docker-image:tag

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main  # Run this job only on the main branch
